---
name: event-data
run-name: event-data ${{event.commits[0].message}} by @${{ github.actor }}
on:
  pull_request:
    types: [opened, closed, reopened]
  push:
    branches:
      - main

jobs:
  eventdata:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
