---
name: generate-workflows
on:
  push:
    branches:
      - main
    paths:
      - deployments/**

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      application_matrix: ${{ steps.matrix.outputs.application_matrix }}
      workflow_file_exist: ${{ steps.check_workflow_file.outputs.files_exists }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2.11.1
        name: Get changed manifests
        id: filter
        with:
          list-files: csv
          filters: |
            changes:
              - added|modified: 'deployments/**'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
      - id: matrix
        name: Generate application matrix
        run: |
          application_matrix="$(python .github/workflows/generate_jobs.py ${{ steps.filter.outputs.changes_files }})"
          echo "application_matrix=$application_matrix" >> $GITHUB_OUTPUT
      - name: Check if workflow file exist
        id: check_workflow_file
        uses: andstor/file-existence-action@v3
        with:
          files: "./.github/workflows/release-${{ fromJSON(steps.matrix.outputs.application_matrix.matrix) }}.yaml"

  create-app-workflow:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.application_matrix }} && changes.outputs.workflow_file_exist != 'true'
    strategy:
      matrix: ${{ fromJSON(needs.changes.outputs.application_matrix) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: create workflow file
        run: |
          cp ./.github/workflows/release-template.tpl ./.github/workflows/release-${{ matrix.application }}.yaml
          sed -i 's/APP_NAME/datadog/g' ./.github/workflows/release-${{ matrix.application }}.yaml
      - name: merge workflow file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto created release workflow for ${{ matrix.application }}."
