---
name: release-test-app
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - deployments/test-app/**
  workflow_call:

jobs:
  call-release-workflow:
    uses: ./.github/workflows/release.yaml
    with:
      application_name: test-app
