---
name: release-gatekeeper
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - deployments/gatekeeper/**
  workflow_call:

jobs:
  call-release-workflow:
    uses: ./.github/workflows/release.yaml
    with:
      application_name: gatekeeper
